2019-03-29 22:31:10 database: wrong user or password; user: ""
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.wisecoders.dbs.rdbms.connect.model.envoy.Envoy.q(Envoy.java:57)
	at com.wisecoders.dbs.rdbms.connect.model.envoy.Envoy.a(Envoy.java:88)
	at com.wisecoders.dbs.rdbms.RdbImport.listSchemas(RdbImport.java:137)
	at com.wisecoders.dbs.rdbms.connect.fx.FxTestConnectivityTask.a(FxTestConnectivityTask.java:44)
	at com.wisecoders.dbs.rdbms.connect.fx.FxTestConnectivityTask.call(FxTestConnectivityTask.java:18)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 24 more
2019-03-29 22:31:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "getFunctions" [50100-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:228)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:385)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3224)
	at com.wisecoders.dbs.rdbms.reverseEngineer.model.ImporterUtils.c(ImporterUtils.java:142)
	at com.wisecoders.dbs.rdbms.RdbImport.listFunctionNames(RdbImport.java:230)
	at com.wisecoders.dbs.rdbms.reverseEngineer.model.StructureImporter.a(StructureImporter.java:49)
	at com.wisecoders.dbs.rdbms.reverseEngineer.model.StructureImporter.<init>(StructureImporter.java:22)
	at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask$1.<init>(FxImportStructureTask.java:39)
	at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask.a(FxImportStructureTask.java:39)
	at com.wisecoders.dbs.rdbms.reverseEngineer.fx.FxImportStructureTask.call(FxImportStructureTask.java:13)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
